### ISSUE TITLE
Consider adding the LICENSE file

### ISSUE THREAD

**Issue by Link-** [DigitalLeaves/AsymmetricCrypto#2]
Hey Ignacio, I just stumbled upon your repo and find this to be a good wrapper for the Security framework. I noticed in your blog post that the license adopted for this code is the MIT license. Do you mind adding this to the repo for clarity? Cheers.

**Comment by DigitalLeaves** [comment]
Hi Link, added the LICENSE.txt file and also included an explicit reference in the README.md.
