### ISSUE TITLE
Can getPublicKeyData be made public again?

### ISSUE THREAD

**Issue by Laban1** [DigitalLeaves/AsymmetricCrypto#3]
Hello,

I just upgraded to Swift 3 and also upgraded AssymetricCrypto.  However, I am using getPublicKeyData which is now fileprivate so my code will not build.  I can easily fix this by simply removing fileprivate, but I wanted to know if there is another way to get the public key data that I should be using.   What I am currently doing:

```
AsymmetricCryptoManager.sharedInstance.createSecureKeyPair({ (success, error) in
   if success {
      let cryptoImportExportManager = CryptoExportImportManager()
      let publicKeyData = AsymmetricCryptoManager.sharedInstance.getPublicKeyData()
      publicKeyPem = cryptoImportExportManager.exportRSAPublicKeyToPEM(publicKeyData!, keyType: kSecAttrKeyTypeRSA as String, keySize: 2048)
                    
   } else {
      Log.error?.message("Error creating key pair: \(error.debugDescription)")
}
```

Perhaps you can remove fileprivate, unless there is a better way to do the above?

Thanks.

**Comment by DigitalLeaves** [comment]
Hi there!

Yes, you should use the getPublicKeyData() method. I don't know how the fileprivate got there, this is an artefact of the swift 3 conversion. I will fix that soon. Thanks for reporting!

**Comment by DigitalLeaves** [comment]
Fixed in last push. Please check.

**Comment by Laban1** [comment]
Thanks for fixing that!  Where can I find the updated source? (not very familiar with Git)

BTW, I also came across the same issue with getPrivateKeyReference.

**Comment by DigitalLeaves** [comment]
Yes, it's as easy as removing the fileprivate thing.

**Comment by Laban1** [comment]
Yes, I know (that's what I did) - I was just curious where I could find
your pushed updated source (I did not see the changes in Git). Just for my
own edification, but not important...

**Comment by DigitalLeaves** [comment]
Oh, yes, sorry, for some reason, the push wasn't showing in the repository. You should be able to see it now. If not, let me know. Thanks again!

**Comment by Laban1** [comment]
No problem - I just checked and I see the changes now!  

Thanks!
