### ISSUE TITLE
There's no way to use my own keys?

### ISSUE THREAD

**Issue by ssaguiar** [DigitalLeaves/AsymmetricCrypto#4]
I wish to use my public key to decrypt a string but I can't find any way to do so.
The asymetric crypto uses a generator for the keys.

Is there any way to make it work with my keys?

**Comment by DigitalLeaves** [comment]
You need to generate a certificate, as I explain in this post: https://digitalleaves.com/blog/2015/10/sharing-public-keys-between-ios-and-the-rest-of-the-world/

Hope it helps!
