### ISSUE TITLE
Can i decrypt my Encrypted message from my Go using EncryptPKCS1v15

### ISSUE THREAD

**Issue by calvinsug** [DigitalLeaves/AsymmetricCrypto#5]
Currently, i'm trying to implement this library to generate public key in my iOS device, and save it in my database through API.

When i send this public key from this library, i modify publicKeyData using https://github.com/DigitalLeaves/CryptoExportImportManager

But, when i encrypt from my backend (GoLang), and i tried to decode the encrypted message from my backend with this code:

       let encryptedData = Data(base64Encoded: encryptedMessage, options: [])
        
        AsymmetricCryptoManager.sharedInstance.decryptMessageWithPrivateKey(encryptedData!) { (success, result, error) -> Void in
            if success {
                print("result: \(result)")
            } else {
                print("Error decoding base64 string: \(error)")
            }
        }

it got error decoding base64 string: Optional(com.myProjects.AsymmetricCryptoException.unableToDecrypt)

After several research, i found, Golang encrypt using EncryptPKCS1v15 (https://github.com/golang/go/blob/master/src/crypto/rsa/pkcs1v15.go)
which make the iOS app failed to decrypt it because it only has PKCS1.

What should i do to decrypt with PKCS1v15 padding ?

**Comment by DigitalLeaves** [comment]
Hello there. The iOS Security framework and libraries are very inflexible and not keen on implementing more than what's needed by Apple. I would have a look at the different PKCSXXX constants in the Security framework and try to match two between iOS and GoLang that you can use. Hope it helps!

**Comment by calvinsug** [comment]
Hi, thanks your reply, so, those two is different right? So, currently, i cannot decrypt it yet using AsymmetricCrypto? But soon, it will be capable to decrypt.

**Comment by calvinsug** [comment]
Hi there, the issue is clear now, decrypt process is run smoothly actually, decoding error occurs because of the decryption result is byte type, not string (i run encryption on []byte type, not the string type)
