### ISSUE TITLE
Unsafe warnings with Swift 5

### ISSUE THREAD

**Issue by Laban1** [DigitalLeaves/AsymmetricCrypto#6]
Hello,

I just upgraded a project where we use AsymmetricCrypto to Swift 5 and we are now getting several warnings "withUnsafeMutableBytes is deprecated...", e.g.::

![image](https://user-images.githubusercontent.com/9595654/79757037-5dfea780-82d0-11ea-8c33-651ba5758039.png)

It would be great if you could handle this.

Thanks.

**Comment by DigitalLeaves** [comment]
Sorry, I am not updating this software currently anymore. Feel free to send a PR and I will review it.
